version: "3.8"
services:
  bblog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bblog
    restart: unless-stopped
    env_file: [.env]
    environment:
      - GIN_MODE=${GIN_MODE:-release}
      - PORT=${PORT:-8080}
    networks: [web]
    volumes:
      - uploads-data:/app/uploads:rw,Z
      - ./.env:/app/.env:ro,Z

volumes:
  uploads-data:

networks:
  web:
    external: true
